// web/src/views/account/course/modules/UnitViewModal.vue
<template>
  <div>
    <j-modal
      :visible="visible"
      :title="unit.unitName"
      @cancel="handleCancel"
      switchFullscreen
      :footer="null"
      :maskClosable="false"
      :width="800"
    >
      <div class="video-area">
        <a-tabs v-if="unit.courseVideo || unit.courseCase">
          <a-tab-pane key="video" tab="视频" v-if="unit.courseVideo">
            <video v-if="unit.courseVideoSource==1" :src="getQiniuFile(unit.courseVideo)" controls="true"></video>
            <video v-if="unit.courseVideoSource==2" :src="unit.courseVideo" controls="true"></video>
            <div v-if="unit.courseVideoSource==3" v-html="unit.courseVideo"></div>
          </a-tab-pane>
          <a-tab-pane key="scratch" tab="案例" v-if="unit.courseCase">
            <iframe id="player" :src="previewCourseCase(unit)"></iframe>
          </a-tab-pane>
        </a-tabs>
        <template v-else>
          <div key="video" tab="视频" v-if="unit.courseVideo">
            <voeideo oncontextmenu="return false;" :src="getFileAccessHttpUrl(unit.courseVideo)" controls="true"></video>
          </div>
          <div key="scratch" tab="案例" v-if="unit.courseCase">
            <!-- <iframe id="player" :src="'/scratch3/player.html?workUrl=' + getFileAccessHttpUrl(unit.courseCase)"></iframe> -->
            <iframe id="player" :src="previewCourseCase(unit)"></iframe>
          </div>
        </template>
      </div>
      <a-divider>本节课资料</a-divider>
      <div>
        <a-row :gutter="24">
          <a-col :span="16">
            <a-card size="small" title="课程说明">
              <div v-html="unit.unitIntro ? unit.unitIntro.replace(/\n/g, '<br>') : ''"></div>
            </a-card>
          </a-col>
          <a-col :span="8">
            <a-collapse defaultActiveKey="0" :bordered="false">
              <template v-slot:expandIcon="props">
                <a-icon type="caret-right" :rotate="props.isActive ? 90 : 0" />
              </template>
              <a-collapse-panel :header="'课后作业'" :style="customStyle">
                <a
                  target="_blank"
                  @click="handleViewCode(unit)"
                  ><a-icon type="edit" />{{ unit.unitName }} 去做作业</a
                >
              </a-collapse-panel>
              <a-collapse-panel v-if="unit.coursePpt" :header="'课程资料'" :style="customStyle">
                <a target="_blank" :href="getFileAccessHttpUrl(unit.coursePpt)"
                  ><a-icon type="edit" />{{ unit.unitName }} 查看资料</a
                >
              </a-collapse-panel>
            </a-collapse>
          </a-col>
        </a-row>
      </div>
    </j-modal>
  </div>
</template>
<script>

import { getFileAccessHttpUrl } from '@/api/manage'
export default {
  name: 'UnitViewModal',
  data() {
    return {
      customStyle: 'background: #f7f7f7;border-radius: 4px;margin-bottom: 24px;border: 0;overflow: hidden',
      visible: false,
      unit: {},
      scratchFrameHref: '',
    }
  },
  methods: {
    getFileAccessHttpUrl,
    handleCancel(e) {
      this.unit = {}
      this.visible = false
    },
    previewCourseCase(unit) {
      let url = this.getFileAccessHttpUrl(unit.courseCase)
      switch(unit.courseWorkType){
        case 1:
          return '/scratch3/player.html?workUrl=' + url
        case 2:
          return '/scratch3/player.html?workUrl=' + url
        case 3:
          return '/scratchjr/editor.html?mode=edit&filepath=' + url
        case 4:
          return '/python/player.html?lang=turtle&url='+ url
      }
    },
    handleViewCode (unit) {
      switch (unit.courseWorkType) {
        case 1:
          window.open('/scratch3/index.html?scene=course&unitId='+unit.id)
          break
        case 2:
          window.open('/scratch3/index.html?scene=course&unitId='+unit.id)
          break
        case 3:
          window.open('/scratchjr/editor.html?mode=edit&filepath=' + this.getFileAccessHttpUrl(unit.courseWork))
          break
        case 4:
          window.open('/python/index.html?lang=turtle&unitId='+unit.id + "&url=" + this.getFileAccessHttpUrl(unit.courseWork))
          break
        default:
          window.open(this.getFileAccessHttpUrl(unit.mediaPath))
      }
  },
  },
}
</script>
<style lang="less" scoped>
.video-area {
  video {
    width: 100%;
    max-height: 500px;
  }
}
#player {
  border: none;
  width: 520px;
  height: 400px;
  margin: auto;
  display: block;
}
</style>

// student-web/src/features/course/UnitViewModal.tsx
import { useEffect } from 'react'
import { Modal, Tabs, Button, Descriptions } from 'antd'
import { useQuery } from '@tanstack/react-query'
import { CourseUnitVO, CourseVO, unitViewLog } from '@/api/course.api'
import { fileUrl } from '@/api/common.api'
import { SafeHtml } from '@/utils/safe-html'
import useBreakpoint from 'antd/es/grid/hooks/useBreakpoint'

interface Props { unit: CourseUnitVO | null; course: CourseVO | null; open: boolean; onClose: () => void }

// 去做作业:按 courseWorkType 跳 IDE
function goIDE(unit: CourseUnitVO, scene: 'course' | 'additional' = 'course') {
  const wt = unit.courseWorkType || 2
  const params = `scene=${scene}&unitId=${unit.id}&workType=${wt}`
  window.open(`/ide?${params}`, '_blank')
}

export default function UnitViewModal({ unit, course, open, onClose }: Props) {
  // 打开时上报浏览日志
  useEffect(() => {
    if (open && unit?.id) { unitViewLog(unit.id).catch(() => {}) }
  }, [open, unit?.id])
  const screens = useBreakpoint()
  const isMobile = !(screens.md ?? false)

  if (!unit) return null

  const videoUrl = unit.courseVideo ? fileUrl(unit.courseVideo) : ''
  const caseUrl = unit.courseCase ? fileUrl(unit.courseCase) : ''

  return (
    <Modal title={unit.unitName} open={open} onCancel={onClose} footer={null} width={isMobile ? '100%' : 800} destroyOnClose>
      <Tabs items={[
        { key: 'video', label: '视频', children: videoUrl ? <video src={videoUrl} controls style={{ width: '100%' }} /> : <div style={{ color: '#999' }}>暂无视频</div> },
        { key: 'case', label: '案例', children: caseUrl ? <iframe src={caseUrl} sandbox="allow-scripts allow-same-origin allow-forms" style={{ width: '100%', height: 400, border: 'none' }} title="案例" /> : <div style={{ color: '#999' }}>暂无案例</div> },
        { key: 'content', label: '课程内容', children: <SafeHtml html={unit.mediaContent || '<span style="color:#999">暂无内容</span>'} /> }
      ]} />

      <Descriptions title="本节课资料" column={1} size="small" style={{ marginTop: 16 }} bordered>
        <Descriptions.Item label="课程说明">{unit.unitIntro || '—'}</Descriptions.Item>
        <Descriptions.Item label="课后作业">
          <Button type="primary" onClick={() => goIDE(unit)}>去做作业</Button>
        </Descriptions.Item>
        <Descriptions.Item label="课程资料">
          {unit.coursePpt ? <a href={fileUrl(unit.coursePpt)} target="_blank" rel="noreferrer">查看资料</a> : '—'}
        </Descriptions.Item>
        <Descriptions.Item label="课程教案">
          {unit.coursePlan ? <a href={fileUrl(unit.coursePlan)} target="_blank" rel="noreferrer">查看教案</a> : '—'}
        </Descriptions.Item>
      </Descriptions>
    </Modal>
  )
}
